export default Object.freeze({
  main: "/",
  // Public routes
  prelogin: "/login",
  register: "/register",
  about: "/about",
  contact: "/contact",
  termsUsers: "/user-terms",
  termsBusiness: "/business-terms",
  cookiePolicie: "/cookie-policie",
  error: "/error",
  subscription: "/subscription",
  // Private routes
  profile: "/profile",
  viewAsProfile: "/:slug/profile",
  wardrobe: "/profile/vault",
  store: "/profile/store",
  arts: "/profile/art",
  following: "/following",
  viewAsFollowing: "/:slug/following",
  spins: "/spins",
  viewAsSpins: "/:slug/spins",
  viewAsStore: "/:slug/profile/store",
  viewAsWardrobe: "/:slug/profile/vault",
  viewAsArts: "/:slug/profile/art",
  tokenizedProduct: "/tokenizedProduct/:token",
  product: "/product/:slug",
  checkoutProduct: "/checkoutProduct/:slug",
  confirmPasson: "/deliveryCheckout/atStore",
  chat: "/:slug/profile/chat",
  dialog: "/:slug/profile/dialog",
  giveback: "/giveback/:old_owner/:product_link",
  worlds: "/profile/architecture",
  viewAsWorlds: "/:slug/profile/architecture",
  brandVault: "/profile/brandvault",
  viewAsBrandVault: "/:slug/profile/brandvault",
  vouchers: "/profile/vouchers",
  viewAsVouchers: "/:slug/profile/vouchers",
  gallery: "/:slug/profile/gallery",
  galleryListView: "/:slug/profile/gallery/list"
});
